### ISSUE TITLE
Problems with Unicode

### ISSUE THREAD

**Issue by mhalano** [tbabej/taskpirate#14]
I installed `bugwarrior` today and got this message during of process of two tasks. I don't know if this problem is related to taskpirate or should I post in the tasklib repo.

Here is the error.
```
ERROR:bugwarrior.db:Unable to modify task: b'Traceback (most recent call last):\n  File "/home/mhalano/.task/hooks/on-modify-pirate", line 43, in <module>\n    task = Task.from_input()\n  File "/home/mhalano/.local/lib/python3.9/site-packages/tasklib/task.py", line 236, in from_input\n    task._load_data(json.loads(input_file.readline().strip()))\n  File "/usr/lib/python3.9/codecs.py", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: \'utf-8\' codec can\'t decode byte 0xed in position 2666: invalid continuation byte\nHook Error: Expected feedback from failing hook script: on-modify-pirate'
Traceback (most recent call last):
  File "/home/mhalano/.local/lib/python3.9/site-packages/bugwarrior/db.py", line 465, in synchronize
    _, updated_task = tw.task_update(issue)
  File "/home/mhalano/.local/lib/python3.9/site-packages/taskw/warrior.py", line 821, in task_update
    self._execute(task_uuid, 'modify', *modification)
  File "/home/mhalano/.local/lib/python3.9/site-packages/taskw/warrior.py", line 497, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)
taskw.exceptions.TaskwarriorError: <unprintable TaskwarriorError object>
```

**Comment by mhalano** [comment]
I found this bug: https://github.com/robgolding/tasklib/issues/82 I think it's the problem.
