### ISSUE TITLE
I think install instructions are outdated

### ISSUE THREAD

**Issue by sdondley** [tbabej/taskpirate#18]
Currently has you download from `pip install --user git+https://github.com/tbabej/tasklib@develop`

But I think this should be update to: `pip install --user git+https://github.com/GothenburgBitFactory/tasklib@develop`

**Comment by sdondley** [comment]
Actually, installing a newer version of tasklib breaks things:

```
> $ t a hi                                                                                                                                                                 [±master ●●]
Traceback (most recent call last):
  File "/Users/steve/.config/taskwarrior/data/work/hooks/on-add-pirate", line 45, in <module>
    for hook in find_hooks('pirate_add'):
  File "/Users/steve/.config/taskwarrior/data/work/hooks/on-add-pirate", line 30, in find_hooks
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/steve/.config/taskwarrior/data/work/hooks/default-time/pirate_add_default_time.py", line 4, in <module>
    from tasklib import Task, local_zone
ImportError: cannot import name 'local_zone' from 'tasklib' (/Users/steve/Library/Python/3.10/lib/python/site-packages/tasklib/__init__.py)
Context 'mail_migration' set. Use 'task context none' to remove.
Hook Error: Expected feedback from failing hook script: on-add-pirate
```
